name: Oh•My Bamboo
favicon: null
layout_spectrum: 0.99578
typography_spectrum: 0.75253
title: Oh•My Bamboo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00a99d'
    - '#005f59'
    - '#7fd4ce'
    - '#37827d'
  brandStrength: 0.09258298226632178
  lightness: 0.20428943913429976
  saturation: 0.27804373344406486
  rhythmicContrast: 0.9442342140246183
purpose: []
